# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-01 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='categories',
        ),
    ]
